---
apiVersion: v1
kind: Service
metadata:
  name: usergrid-api
  labels:
    app: usergrid
    tier: backend
    role: rest
spec:
  ports:
  - port: 8080
  selector:
    app: usergrid
    tier: backend
    role: master

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usergrid
  labels:
    app: usergrid
    role: master
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: usergrid
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: yep1/usergrid
        env:
          - name: CASSANDRA_PORT_9160_TCP_ADDR
            value: "$(CASSANDRA_THRIFT_SERVICE_HOST)"
          - name: CASSANDRA_PORT_9160_TCP_PORT
            value: "$(CASSANDRA_THRIFT_SERVICE_PORT)"
          - name: ELASTICSEARCH_PORT_9300_TCP_ADDR
            value: "$(ELASTICSEARCH_NATIVE_SERVICE_HOST)"
          - name: ELASTICSEARCH_PORT_9300_TCP_PORT
            value: "$(ELASTICSEARCH_NATIVE_SERVICE_PORT)"
          - name: ADMIN_PASS
            value: "password"
          - name: ADMIN_MAIL
            value: "admin@example.com"
          - name: ORG_NAME
            value: "whirlpool"
          - name: APP_NAME
            value: "violet"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080

